### ISSUE TITLE
How to use the Emo Dot Matrix with Python 3?

### ISSUE THREAD

**Issue by Konseq** [sunfounder/SunFounder_Emo#1]
Hi,

for a Raspberry Pi student project I got the Emo Dot Matrix and downloaded the files from here. The example code seems to be for Python 2, but I need to do my project in Python 3 and have no experience how to write the code myself. Is there any help available?

Thanks a lot in advance.

**Comment by Konseq** [comment]
I have further worked on the issue. The code is running under Python 3 now, but when I run any of the example codes given in this repository the LED matrix does not change at all. I activated the SPI interface and also the files /dev/spidev0.0 and /dev/spidev0.1 do exist. Yet the commands which are sent by the code to the spi interface do not seem to work. I checked wiring many times and those are correct too. I followed all steps of the wiki (http://wiki.sunfounder.cc/index.php?title=24x8_LED_Dot_Matrix_Module_-_Emo) yet it still doesn't work. Please help.

**Comment by glenneroo** [comment]
How did you get it running on Python 3? I only get the following error:
Traceback (most recent call last):
  File "examples/animate.py", line 2, in <module>
    from SunFounder_Emo import Emo
  File "/usr/local/lib/python3.5/dist-packages/SunFounder_Emo-1.1.0-py3.5.egg/SunFounder_Emo/__init__.py", line 1, in <module>
ImportError: No module named 'emo'

**Comment by sunfounder** [comment]
Hi Glenn,
Attached the picture for you reference,please add  .  in front of the SunFounder_Emo on the second line.



Best Regards,
SunFounder Team
 
From: glenneroo
Date: 2019-04-24 19:23
To: sunfounder/SunFounder_Emo
CC: Subscribed
Subject: Re: [sunfounder/SunFounder_Emo] How to use the Emo Dot Matrix with Python 3? (#1)
How did you get it running on Python 3? I only get the following error:
Traceback (most recent call last):
File "examples/animate.py", line 2, in 
from SunFounder_Emo import Emo
File "/usr/local/lib/python3.5/dist-packages/SunFounder_Emo-1.1.0-py3.5.egg/SunFounder_Emo/init.py", line 1, in 
ImportError: No module named 'emo'

**Comment by glenneroo** [comment]
You attached a picture where? I don't see anything.
I added the "." to 'animate.py' like this:
```
from .Sunfounder_Emo import Emo
```
or like this:
```
from . Sunfounder_Emo import Emo
```

But in both cases I only get this error:
```
Traceback (most recent call last):
  File "animate.py", line 2, in <module>
    from .SunFounder_Emo import Emo
SystemError: Parent module '' not loaded, cannot perform relative import
```
